<?php
function generateStaticPage($slug, $html_content) {
    $dir = '../../pages/';
    if(!is_dir($dir)) mkdir($dir, 0777, true);
    
    $file = $dir . $slug . '/index.php';
    $content = "<?php
// Generated by CMS Pages Builder
header('Content-Type: text/html; charset=UTF-8');
header('X-Generated-By: CMS-Pages-Builder');
?>
<!DOCTYPE html>
<html lang='id'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>" . addslashes($slug) . "</title>
</head>
<body>
    " . $html_content . "
</body>
</html>";

    file_put_contents($file, $content);
    
    // Buat .htaccess untuk clean URL
    $htaccess = $dir . $slug . '/.htaccess';
    file_put_contents($htaccess, "RewriteEngine On\nRewriteRule ^$ index.php [L]");
}
?>